language: node_js

node_js:
  - "12.14.0"

cache:
  npm: true
  directories:
    - public
    - .cache

script:
    - npm run build

deploy:
  provider: pages
  skin-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  target_branch: gh-pages
  on:
    branch: main